<?php
/**
 * ModelliModelloBody
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Sprint - Documentazione
 *
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.71
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ModelliModelloBody Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ModelliModelloBody implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'modelli_modello_body';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'descrizione' => '',
        'speditore' => '',
        'destinatario' => '',
        'trasporto' => '',
        'osservazioni' => '',
        'paese_destinazione' => '',
        'azienda_produttrice' => '',
        'azienda_modifiche' => '',
        'documentazione_allegata' => '',
        'giacenza_merci' => '',
        'ncopie' => '',
        'nvisti' => '',
        'nleg' => '',
        'fatt_firmata' => '',
        'notecciaa' => ''
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'descrizione' => null,
        'speditore' => null,
        'destinatario' => null,
        'trasporto' => null,
        'osservazioni' => null,
        'paese_destinazione' => null,
        'azienda_produttrice' => null,
        'azienda_modifiche' => null,
        'documentazione_allegata' => null,
        'giacenza_merci' => null,
        'ncopie' => null,
        'nvisti' => null,
        'nleg' => null,
        'fatt_firmata' => null,
        'notecciaa' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'descrizione' => 'descrizione',
        'speditore' => 'speditore',
        'destinatario' => 'destinatario',
        'trasporto' => 'trasporto',
        'osservazioni' => 'osservazioni',
        'paese_destinazione' => 'paese_destinazione',
        'azienda_produttrice' => 'azienda_produttrice',
        'azienda_modifiche' => 'azienda_modifiche',
        'documentazione_allegata' => 'documentazione_allegata',
        'giacenza_merci' => 'giacenza_merci',
        'ncopie' => 'ncopie',
        'nvisti' => 'nvisti',
        'nleg' => 'nleg',
        'fatt_firmata' => 'fatt_firmata',
        'notecciaa' => 'notecciaa'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'descrizione' => 'setDescrizione',
        'speditore' => 'setSpeditore',
        'destinatario' => 'setDestinatario',
        'trasporto' => 'setTrasporto',
        'osservazioni' => 'setOsservazioni',
        'paese_destinazione' => 'setPaeseDestinazione',
        'azienda_produttrice' => 'setAziendaProduttrice',
        'azienda_modifiche' => 'setAziendaModifiche',
        'documentazione_allegata' => 'setDocumentazioneAllegata',
        'giacenza_merci' => 'setGiacenzaMerci',
        'ncopie' => 'setNcopie',
        'nvisti' => 'setNvisti',
        'nleg' => 'setNleg',
        'fatt_firmata' => 'setFattFirmata',
        'notecciaa' => 'setNotecciaa'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'descrizione' => 'getDescrizione',
        'speditore' => 'getSpeditore',
        'destinatario' => 'getDestinatario',
        'trasporto' => 'getTrasporto',
        'osservazioni' => 'getOsservazioni',
        'paese_destinazione' => 'getPaeseDestinazione',
        'azienda_produttrice' => 'getAziendaProduttrice',
        'azienda_modifiche' => 'getAziendaModifiche',
        'documentazione_allegata' => 'getDocumentazioneAllegata',
        'giacenza_merci' => 'getGiacenzaMerci',
        'ncopie' => 'getNcopie',
        'nvisti' => 'getNvisti',
        'nleg' => 'getNleg',
        'fatt_firmata' => 'getFattFirmata',
        'notecciaa' => 'getNotecciaa'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['descrizione'] = isset($data['descrizione']) ? $data['descrizione'] : null;
        $this->container['speditore'] = isset($data['speditore']) ? $data['speditore'] : null;
        $this->container['destinatario'] = isset($data['destinatario']) ? $data['destinatario'] : null;
        $this->container['trasporto'] = isset($data['trasporto']) ? $data['trasporto'] : null;
        $this->container['osservazioni'] = isset($data['osservazioni']) ? $data['osservazioni'] : null;
        $this->container['paese_destinazione'] = isset($data['paese_destinazione']) ? $data['paese_destinazione'] : null;
        $this->container['azienda_produttrice'] = isset($data['azienda_produttrice']) ? $data['azienda_produttrice'] : null;
        $this->container['azienda_modifiche'] = isset($data['azienda_modifiche']) ? $data['azienda_modifiche'] : null;
        $this->container['documentazione_allegata'] = isset($data['documentazione_allegata']) ? $data['documentazione_allegata'] : null;
        $this->container['giacenza_merci'] = isset($data['giacenza_merci']) ? $data['giacenza_merci'] : null;
        $this->container['ncopie'] = isset($data['ncopie']) ? $data['ncopie'] : null;
        $this->container['nvisti'] = isset($data['nvisti']) ? $data['nvisti'] : null;
        $this->container['nleg'] = isset($data['nleg']) ? $data['nleg'] : null;
        $this->container['fatt_firmata'] = isset($data['fatt_firmata']) ? $data['fatt_firmata'] : null;
        $this->container['notecciaa'] = isset($data['notecciaa']) ? $data['notecciaa'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['descrizione'] === null) {
            $invalidProperties[] = "'descrizione' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets descrizione
     *
     * @return 
     */
    public function getDescrizione()
    {
        return $this->container['descrizione'];
    }

    /**
     * Sets descrizione
     *
     * @param  $descrizione descrizione
     *
     * @return $this
     */
    public function setDescrizione($descrizione)
    {
        $this->container['descrizione'] = $descrizione;

        return $this;
    }

    /**
     * Gets speditore
     *
     * @return 
     */
    public function getSpeditore()
    {
        return $this->container['speditore'];
    }

    /**
     * Sets speditore
     *
     * @param  $speditore speditore
     *
     * @return $this
     */
    public function setSpeditore($speditore)
    {
        $this->container['speditore'] = $speditore;

        return $this;
    }

    /**
     * Gets destinatario
     *
     * @return 
     */
    public function getDestinatario()
    {
        return $this->container['destinatario'];
    }

    /**
     * Sets destinatario
     *
     * @param  $destinatario destinatario
     *
     * @return $this
     */
    public function setDestinatario($destinatario)
    {
        $this->container['destinatario'] = $destinatario;

        return $this;
    }

    /**
     * Gets trasporto
     *
     * @return 
     */
    public function getTrasporto()
    {
        return $this->container['trasporto'];
    }

    /**
     * Sets trasporto
     *
     * @param  $trasporto 'paese_origine' => 'max:256',
     *
     * @return $this
     */
    public function setTrasporto($trasporto)
    {
        $this->container['trasporto'] = $trasporto;

        return $this;
    }

    /**
     * Gets osservazioni
     *
     * @return 
     */
    public function getOsservazioni()
    {
        return $this->container['osservazioni'];
    }

    /**
     * Sets osservazioni
     *
     * @param  $osservazioni osservazioni
     *
     * @return $this
     */
    public function setOsservazioni($osservazioni)
    {
        $this->container['osservazioni'] = $osservazioni;

        return $this;
    }

    /**
     * Gets paese_destinazione
     *
     * @return 
     */
    public function getPaeseDestinazione()
    {
        return $this->container['paese_destinazione'];
    }

    /**
     * Sets paese_destinazione
     *
     * @param  $paese_destinazione 'merci' => 'max:3500', 'quantita' => 'max:3500',
     *
     * @return $this
     */
    public function setPaeseDestinazione($paese_destinazione)
    {
        $this->container['paese_destinazione'] = $paese_destinazione;

        return $this;
    }

    /**
     * Gets azienda_produttrice
     *
     * @return 
     */
    public function getAziendaProduttrice()
    {
        return $this->container['azienda_produttrice'];
    }

    /**
     * Sets azienda_produttrice
     *
     * @param  $azienda_produttrice azienda_produttrice
     *
     * @return $this
     */
    public function setAziendaProduttrice($azienda_produttrice)
    {
        $this->container['azienda_produttrice'] = $azienda_produttrice;

        return $this;
    }

    /**
     * Gets azienda_modifiche
     *
     * @return 
     */
    public function getAziendaModifiche()
    {
        return $this->container['azienda_modifiche'];
    }

    /**
     * Sets azienda_modifiche
     *
     * @param  $azienda_modifiche azienda_modifiche
     *
     * @return $this
     */
    public function setAziendaModifiche($azienda_modifiche)
    {
        $this->container['azienda_modifiche'] = $azienda_modifiche;

        return $this;
    }

    /**
     * Gets documentazione_allegata
     *
     * @return 
     */
    public function getDocumentazioneAllegata()
    {
        return $this->container['documentazione_allegata'];
    }

    /**
     * Sets documentazione_allegata
     *
     * @param  $documentazione_allegata documentazione_allegata
     *
     * @return $this
     */
    public function setDocumentazioneAllegata($documentazione_allegata)
    {
        $this->container['documentazione_allegata'] = $documentazione_allegata;

        return $this;
    }

    /**
     * Gets giacenza_merci
     *
     * @return 
     */
    public function getGiacenzaMerci()
    {
        return $this->container['giacenza_merci'];
    }

    /**
     * Sets giacenza_merci
     *
     * @param  $giacenza_merci giacenza_merci
     *
     * @return $this
     */
    public function setGiacenzaMerci($giacenza_merci)
    {
        $this->container['giacenza_merci'] = $giacenza_merci;

        return $this;
    }

    /**
     * Gets ncopie
     *
     * @return 
     */
    public function getNcopie()
    {
        return $this->container['ncopie'];
    }

    /**
     * Sets ncopie
     *
     * @param  $ncopie ncopie
     *
     * @return $this
     */
    public function setNcopie($ncopie)
    {
        $this->container['ncopie'] = $ncopie;

        return $this;
    }

    /**
     * Gets nvisti
     *
     * @return 
     */
    public function getNvisti()
    {
        return $this->container['nvisti'];
    }

    /**
     * Sets nvisti
     *
     * @param  $nvisti nvisti
     *
     * @return $this
     */
    public function setNvisti($nvisti)
    {
        $this->container['nvisti'] = $nvisti;

        return $this;
    }

    /**
     * Gets nleg
     *
     * @return 
     */
    public function getNleg()
    {
        return $this->container['nleg'];
    }

    /**
     * Sets nleg
     *
     * @param  $nleg nleg
     *
     * @return $this
     */
    public function setNleg($nleg)
    {
        $this->container['nleg'] = $nleg;

        return $this;
    }

    /**
     * Gets fatt_firmata
     *
     * @return 
     */
    public function getFattFirmata()
    {
        return $this->container['fatt_firmata'];
    }

    /**
     * Sets fatt_firmata
     *
     * @param  $fatt_firmata fatt_firmata
     *
     * @return $this
     */
    public function setFattFirmata($fatt_firmata)
    {
        $this->container['fatt_firmata'] = $fatt_firmata;

        return $this;
    }

    /**
     * Gets notecciaa
     *
     * @return 
     */
    public function getNotecciaa()
    {
        return $this->container['notecciaa'];
    }

    /**
     * Sets notecciaa
     *
     * @param  $notecciaa notecciaa
     *
     * @return $this
     */
    public function setNotecciaa($notecciaa)
    {
        $this->container['notecciaa'] = $notecciaa;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
