<?php
/**
 * V2modelliUpdateRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Sprint - Documentazione
 *
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V2modelliUpdateRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V2modelliUpdateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v2modelli_update_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'descrizione' => 'string',
        'speditore' => 'string',
        'destinatario' => 'string',
        'trasporto' => 'string',
        'osservazioni' => 'string',
        'paese_destinazione' => 'string',
        'azienda_produttrice' => 'string',
        'azienda_modifiche' => 'string',
        'documentazione_allegata' => 'string',
        'giacenza_merci' => 'string',
        'ncopie' => 'string',
        'nvisti' => 'string',
        'nleg' => 'string',
        'fatt_firmata' => 'string',
        'notecciaa' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'descrizione' => null,
        'speditore' => null,
        'destinatario' => null,
        'trasporto' => null,
        'osservazioni' => null,
        'paese_destinazione' => null,
        'azienda_produttrice' => null,
        'azienda_modifiche' => null,
        'documentazione_allegata' => null,
        'giacenza_merci' => null,
        'ncopie' => null,
        'nvisti' => null,
        'nleg' => null,
        'fatt_firmata' => null,
        'notecciaa' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'descrizione' => false,
        'speditore' => false,
        'destinatario' => false,
        'trasporto' => false,
        'osservazioni' => false,
        'paese_destinazione' => false,
        'azienda_produttrice' => false,
        'azienda_modifiche' => false,
        'documentazione_allegata' => false,
        'giacenza_merci' => false,
        'ncopie' => false,
        'nvisti' => false,
        'nleg' => false,
        'fatt_firmata' => false,
        'notecciaa' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'descrizione' => 'descrizione',
        'speditore' => 'speditore',
        'destinatario' => 'destinatario',
        'trasporto' => 'trasporto',
        'osservazioni' => 'osservazioni',
        'paese_destinazione' => 'paese_destinazione',
        'azienda_produttrice' => 'azienda_produttrice',
        'azienda_modifiche' => 'azienda_modifiche',
        'documentazione_allegata' => 'documentazione_allegata',
        'giacenza_merci' => 'giacenza_merci',
        'ncopie' => 'ncopie',
        'nvisti' => 'nvisti',
        'nleg' => 'nleg',
        'fatt_firmata' => 'fatt_firmata',
        'notecciaa' => 'notecciaa'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'descrizione' => 'setDescrizione',
        'speditore' => 'setSpeditore',
        'destinatario' => 'setDestinatario',
        'trasporto' => 'setTrasporto',
        'osservazioni' => 'setOsservazioni',
        'paese_destinazione' => 'setPaeseDestinazione',
        'azienda_produttrice' => 'setAziendaProduttrice',
        'azienda_modifiche' => 'setAziendaModifiche',
        'documentazione_allegata' => 'setDocumentazioneAllegata',
        'giacenza_merci' => 'setGiacenzaMerci',
        'ncopie' => 'setNcopie',
        'nvisti' => 'setNvisti',
        'nleg' => 'setNleg',
        'fatt_firmata' => 'setFattFirmata',
        'notecciaa' => 'setNotecciaa'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'descrizione' => 'getDescrizione',
        'speditore' => 'getSpeditore',
        'destinatario' => 'getDestinatario',
        'trasporto' => 'getTrasporto',
        'osservazioni' => 'getOsservazioni',
        'paese_destinazione' => 'getPaeseDestinazione',
        'azienda_produttrice' => 'getAziendaProduttrice',
        'azienda_modifiche' => 'getAziendaModifiche',
        'documentazione_allegata' => 'getDocumentazioneAllegata',
        'giacenza_merci' => 'getGiacenzaMerci',
        'ncopie' => 'getNcopie',
        'nvisti' => 'getNvisti',
        'nleg' => 'getNleg',
        'fatt_firmata' => 'getFattFirmata',
        'notecciaa' => 'getNotecciaa'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('descrizione', $data ?? [], null);
        $this->setIfExists('speditore', $data ?? [], null);
        $this->setIfExists('destinatario', $data ?? [], null);
        $this->setIfExists('trasporto', $data ?? [], null);
        $this->setIfExists('osservazioni', $data ?? [], null);
        $this->setIfExists('paese_destinazione', $data ?? [], null);
        $this->setIfExists('azienda_produttrice', $data ?? [], null);
        $this->setIfExists('azienda_modifiche', $data ?? [], null);
        $this->setIfExists('documentazione_allegata', $data ?? [], null);
        $this->setIfExists('giacenza_merci', $data ?? [], null);
        $this->setIfExists('ncopie', $data ?? [], '0');
        $this->setIfExists('nvisti', $data ?? [], '0');
        $this->setIfExists('nleg', $data ?? [], '0');
        $this->setIfExists('fatt_firmata', $data ?? [], 'S');
        $this->setIfExists('notecciaa', $data ?? [], '');
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['descrizione'] === null) {
            $invalidProperties[] = "'descrizione' can't be null";
        }
        if ((mb_strlen($this->container['descrizione']) > 60)) {
            $invalidProperties[] = "invalid value for 'descrizione', the character length must be smaller than or equal to 60.";
        }

        if (!is_null($this->container['speditore']) && (mb_strlen($this->container['speditore']) > 240)) {
            $invalidProperties[] = "invalid value for 'speditore', the character length must be smaller than or equal to 240.";
        }

        if (!is_null($this->container['destinatario']) && (mb_strlen($this->container['destinatario']) > 800)) {
            $invalidProperties[] = "invalid value for 'destinatario', the character length must be smaller than or equal to 800.";
        }

        if (!is_null($this->container['trasporto']) && (mb_strlen($this->container['trasporto']) > 200)) {
            $invalidProperties[] = "invalid value for 'trasporto', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['osservazioni']) && (mb_strlen($this->container['osservazioni']) > 500)) {
            $invalidProperties[] = "invalid value for 'osservazioni', the character length must be smaller than or equal to 500.";
        }

        if (!is_null($this->container['paese_destinazione']) && (mb_strlen($this->container['paese_destinazione']) > 256)) {
            $invalidProperties[] = "invalid value for 'paese_destinazione', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['azienda_produttrice']) && (mb_strlen($this->container['azienda_produttrice']) > 850)) {
            $invalidProperties[] = "invalid value for 'azienda_produttrice', the character length must be smaller than or equal to 850.";
        }

        if (!is_null($this->container['azienda_modifiche']) && (mb_strlen($this->container['azienda_modifiche']) > 850)) {
            $invalidProperties[] = "invalid value for 'azienda_modifiche', the character length must be smaller than or equal to 850.";
        }

        if (!is_null($this->container['documentazione_allegata']) && (mb_strlen($this->container['documentazione_allegata']) > 850)) {
            $invalidProperties[] = "invalid value for 'documentazione_allegata', the character length must be smaller than or equal to 850.";
        }

        if (!is_null($this->container['giacenza_merci']) && (mb_strlen($this->container['giacenza_merci']) > 200)) {
            $invalidProperties[] = "invalid value for 'giacenza_merci', the character length must be smaller than or equal to 200.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets descrizione
     *
     * @return string
     */
    public function getDescrizione()
    {
        return $this->container['descrizione'];
    }

    /**
     * Sets descrizione
     *
     * @param string $descrizione descrizione
     *
     * @return self
     */
    public function setDescrizione($descrizione)
    {
        if (is_null($descrizione)) {
            throw new \InvalidArgumentException('non-nullable descrizione cannot be null');
        }
        if ((mb_strlen($descrizione) > 60)) {
            throw new \InvalidArgumentException('invalid length for $descrizione when calling V2modelliUpdateRequest., must be smaller than or equal to 60.');
        }

        $this->container['descrizione'] = $descrizione;

        return $this;
    }

    /**
     * Gets speditore
     *
     * @return string|null
     */
    public function getSpeditore()
    {
        return $this->container['speditore'];
    }

    /**
     * Sets speditore
     *
     * @param string|null $speditore speditore
     *
     * @return self
     */
    public function setSpeditore($speditore)
    {
        if (is_null($speditore)) {
            throw new \InvalidArgumentException('non-nullable speditore cannot be null');
        }
        if ((mb_strlen($speditore) > 240)) {
            throw new \InvalidArgumentException('invalid length for $speditore when calling V2modelliUpdateRequest., must be smaller than or equal to 240.');
        }

        $this->container['speditore'] = $speditore;

        return $this;
    }

    /**
     * Gets destinatario
     *
     * @return string|null
     */
    public function getDestinatario()
    {
        return $this->container['destinatario'];
    }

    /**
     * Sets destinatario
     *
     * @param string|null $destinatario destinatario
     *
     * @return self
     */
    public function setDestinatario($destinatario)
    {
        if (is_null($destinatario)) {
            throw new \InvalidArgumentException('non-nullable destinatario cannot be null');
        }
        if ((mb_strlen($destinatario) > 800)) {
            throw new \InvalidArgumentException('invalid length for $destinatario when calling V2modelliUpdateRequest., must be smaller than or equal to 800.');
        }

        $this->container['destinatario'] = $destinatario;

        return $this;
    }

    /**
     * Gets trasporto
     *
     * @return string|null
     */
    public function getTrasporto()
    {
        return $this->container['trasporto'];
    }

    /**
     * Sets trasporto
     *
     * @param string|null $trasporto 'paese_origine' => 'max:256',
     *
     * @return self
     */
    public function setTrasporto($trasporto)
    {
        if (is_null($trasporto)) {
            throw new \InvalidArgumentException('non-nullable trasporto cannot be null');
        }
        if ((mb_strlen($trasporto) > 200)) {
            throw new \InvalidArgumentException('invalid length for $trasporto when calling V2modelliUpdateRequest., must be smaller than or equal to 200.');
        }

        $this->container['trasporto'] = $trasporto;

        return $this;
    }

    /**
     * Gets osservazioni
     *
     * @return string|null
     */
    public function getOsservazioni()
    {
        return $this->container['osservazioni'];
    }

    /**
     * Sets osservazioni
     *
     * @param string|null $osservazioni osservazioni
     *
     * @return self
     */
    public function setOsservazioni($osservazioni)
    {
        if (is_null($osservazioni)) {
            throw new \InvalidArgumentException('non-nullable osservazioni cannot be null');
        }
        if ((mb_strlen($osservazioni) > 500)) {
            throw new \InvalidArgumentException('invalid length for $osservazioni when calling V2modelliUpdateRequest., must be smaller than or equal to 500.');
        }

        $this->container['osservazioni'] = $osservazioni;

        return $this;
    }

    /**
     * Gets paese_destinazione
     *
     * @return string|null
     */
    public function getPaeseDestinazione()
    {
        return $this->container['paese_destinazione'];
    }

    /**
     * Sets paese_destinazione
     *
     * @param string|null $paese_destinazione 'merci' => 'max:3500', 'quantita' => 'max:3500',
     *
     * @return self
     */
    public function setPaeseDestinazione($paese_destinazione)
    {
        if (is_null($paese_destinazione)) {
            throw new \InvalidArgumentException('non-nullable paese_destinazione cannot be null');
        }
        if ((mb_strlen($paese_destinazione) > 256)) {
            throw new \InvalidArgumentException('invalid length for $paese_destinazione when calling V2modelliUpdateRequest., must be smaller than or equal to 256.');
        }

        $this->container['paese_destinazione'] = $paese_destinazione;

        return $this;
    }

    /**
     * Gets azienda_produttrice
     *
     * @return string|null
     */
    public function getAziendaProduttrice()
    {
        return $this->container['azienda_produttrice'];
    }

    /**
     * Sets azienda_produttrice
     *
     * @param string|null $azienda_produttrice azienda_produttrice
     *
     * @return self
     */
    public function setAziendaProduttrice($azienda_produttrice)
    {
        if (is_null($azienda_produttrice)) {
            throw new \InvalidArgumentException('non-nullable azienda_produttrice cannot be null');
        }
        if ((mb_strlen($azienda_produttrice) > 850)) {
            throw new \InvalidArgumentException('invalid length for $azienda_produttrice when calling V2modelliUpdateRequest., must be smaller than or equal to 850.');
        }

        $this->container['azienda_produttrice'] = $azienda_produttrice;

        return $this;
    }

    /**
     * Gets azienda_modifiche
     *
     * @return string|null
     */
    public function getAziendaModifiche()
    {
        return $this->container['azienda_modifiche'];
    }

    /**
     * Sets azienda_modifiche
     *
     * @param string|null $azienda_modifiche azienda_modifiche
     *
     * @return self
     */
    public function setAziendaModifiche($azienda_modifiche)
    {
        if (is_null($azienda_modifiche)) {
            throw new \InvalidArgumentException('non-nullable azienda_modifiche cannot be null');
        }
        if ((mb_strlen($azienda_modifiche) > 850)) {
            throw new \InvalidArgumentException('invalid length for $azienda_modifiche when calling V2modelliUpdateRequest., must be smaller than or equal to 850.');
        }

        $this->container['azienda_modifiche'] = $azienda_modifiche;

        return $this;
    }

    /**
     * Gets documentazione_allegata
     *
     * @return string|null
     */
    public function getDocumentazioneAllegata()
    {
        return $this->container['documentazione_allegata'];
    }

    /**
     * Sets documentazione_allegata
     *
     * @param string|null $documentazione_allegata documentazione_allegata
     *
     * @return self
     */
    public function setDocumentazioneAllegata($documentazione_allegata)
    {
        if (is_null($documentazione_allegata)) {
            throw new \InvalidArgumentException('non-nullable documentazione_allegata cannot be null');
        }
        if ((mb_strlen($documentazione_allegata) > 850)) {
            throw new \InvalidArgumentException('invalid length for $documentazione_allegata when calling V2modelliUpdateRequest., must be smaller than or equal to 850.');
        }

        $this->container['documentazione_allegata'] = $documentazione_allegata;

        return $this;
    }

    /**
     * Gets giacenza_merci
     *
     * @return string|null
     */
    public function getGiacenzaMerci()
    {
        return $this->container['giacenza_merci'];
    }

    /**
     * Sets giacenza_merci
     *
     * @param string|null $giacenza_merci giacenza_merci
     *
     * @return self
     */
    public function setGiacenzaMerci($giacenza_merci)
    {
        if (is_null($giacenza_merci)) {
            throw new \InvalidArgumentException('non-nullable giacenza_merci cannot be null');
        }
        if ((mb_strlen($giacenza_merci) > 200)) {
            throw new \InvalidArgumentException('invalid length for $giacenza_merci when calling V2modelliUpdateRequest., must be smaller than or equal to 200.');
        }

        $this->container['giacenza_merci'] = $giacenza_merci;

        return $this;
    }

    /**
     * Gets ncopie
     *
     * @return string|null
     */
    public function getNcopie()
    {
        return $this->container['ncopie'];
    }

    /**
     * Sets ncopie
     *
     * @param string|null $ncopie ncopie
     *
     * @return self
     */
    public function setNcopie($ncopie)
    {
        if (is_null($ncopie)) {
            throw new \InvalidArgumentException('non-nullable ncopie cannot be null');
        }
        $this->container['ncopie'] = $ncopie;

        return $this;
    }

    /**
     * Gets nvisti
     *
     * @return string|null
     */
    public function getNvisti()
    {
        return $this->container['nvisti'];
    }

    /**
     * Sets nvisti
     *
     * @param string|null $nvisti nvisti
     *
     * @return self
     */
    public function setNvisti($nvisti)
    {
        if (is_null($nvisti)) {
            throw new \InvalidArgumentException('non-nullable nvisti cannot be null');
        }
        $this->container['nvisti'] = $nvisti;

        return $this;
    }

    /**
     * Gets nleg
     *
     * @return string|null
     */
    public function getNleg()
    {
        return $this->container['nleg'];
    }

    /**
     * Sets nleg
     *
     * @param string|null $nleg nleg
     *
     * @return self
     */
    public function setNleg($nleg)
    {
        if (is_null($nleg)) {
            throw new \InvalidArgumentException('non-nullable nleg cannot be null');
        }
        $this->container['nleg'] = $nleg;

        return $this;
    }

    /**
     * Gets fatt_firmata
     *
     * @return string|null
     */
    public function getFattFirmata()
    {
        return $this->container['fatt_firmata'];
    }

    /**
     * Sets fatt_firmata
     *
     * @param string|null $fatt_firmata fatt_firmata
     *
     * @return self
     */
    public function setFattFirmata($fatt_firmata)
    {
        if (is_null($fatt_firmata)) {
            throw new \InvalidArgumentException('non-nullable fatt_firmata cannot be null');
        }
        $this->container['fatt_firmata'] = $fatt_firmata;

        return $this;
    }

    /**
     * Gets notecciaa
     *
     * @return string|null
     */
    public function getNotecciaa()
    {
        return $this->container['notecciaa'];
    }

    /**
     * Sets notecciaa
     *
     * @param string|null $notecciaa notecciaa
     *
     * @return self
     */
    public function setNotecciaa($notecciaa)
    {
        if (is_null($notecciaa)) {
            throw new \InvalidArgumentException('non-nullable notecciaa cannot be null');
        }
        $this->container['notecciaa'] = $notecciaa;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


