<?php
/**
 * V2richiesteStoreRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Sprint - Documentazione
 *
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V2richiesteStoreRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V2richiesteStoreRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v2richieste_store_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'descrizione' => 'string',
        'numero_copie' => 'string',
        'modello_id' => 'string',
        'speditore' => 'string',
        'destinatario' => 'string',
        'paese_origine' => 'string',
        'trasporto' => 'string',
        'osservazioni' => 'string',
        'merci' => 'string',
        'quantita' => 'string',
        'paese_dest' => 'string',
        'valore_merce' => 'string',
        'numero_aut' => 'string',
        'paese_comunitario' => 'string',
        'produzione' => 'string',
        'azienda_produttrice' => 'string',
        'modifiche' => 'string',
        'azienda_modifiche' => 'string',
        'paese_extraue' => 'string',
        'documentazione_allegata' => 'string',
        'giacenza_merci' => 'string',
        'annotazioni_mittente' => 'string',
        'annotazioni_interne' => 'string',
        'proforma' => 'string',
        'urgente' => 'string',
        'email_contatto' => 'string',
        'cciaa' => '\OpenAPI\Client\Model\V2richiesteStoreRequestCciaa'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'descrizione' => null,
        'numero_copie' => null,
        'modello_id' => null,
        'speditore' => null,
        'destinatario' => null,
        'paese_origine' => null,
        'trasporto' => null,
        'osservazioni' => null,
        'merci' => null,
        'quantita' => null,
        'paese_dest' => null,
        'valore_merce' => null,
        'numero_aut' => null,
        'paese_comunitario' => null,
        'produzione' => null,
        'azienda_produttrice' => null,
        'modifiche' => null,
        'azienda_modifiche' => null,
        'paese_extraue' => null,
        'documentazione_allegata' => null,
        'giacenza_merci' => null,
        'annotazioni_mittente' => null,
        'annotazioni_interne' => null,
        'proforma' => null,
        'urgente' => null,
        'email_contatto' => null,
        'cciaa' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'descrizione' => false,
        'numero_copie' => false,
        'modello_id' => false,
        'speditore' => false,
        'destinatario' => false,
        'paese_origine' => false,
        'trasporto' => false,
        'osservazioni' => false,
        'merci' => false,
        'quantita' => false,
        'paese_dest' => false,
        'valore_merce' => false,
        'numero_aut' => false,
        'paese_comunitario' => false,
        'produzione' => false,
        'azienda_produttrice' => false,
        'modifiche' => false,
        'azienda_modifiche' => false,
        'paese_extraue' => false,
        'documentazione_allegata' => false,
        'giacenza_merci' => false,
        'annotazioni_mittente' => false,
        'annotazioni_interne' => false,
        'proforma' => false,
        'urgente' => false,
        'email_contatto' => false,
        'cciaa' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'descrizione' => 'descrizione',
        'numero_copie' => 'numero_copie',
        'modello_id' => 'modello_id',
        'speditore' => 'speditore',
        'destinatario' => 'destinatario',
        'paese_origine' => 'paese_origine',
        'trasporto' => 'trasporto',
        'osservazioni' => 'osservazioni',
        'merci' => 'merci',
        'quantita' => 'quantita',
        'paese_dest' => 'paese_dest',
        'valore_merce' => 'valore_merce',
        'numero_aut' => 'numero_aut',
        'paese_comunitario' => 'paese_comunitario',
        'produzione' => 'produzione',
        'azienda_produttrice' => 'azienda_produttrice',
        'modifiche' => 'modifiche',
        'azienda_modifiche' => 'azienda_modifiche',
        'paese_extraue' => 'paese_extraue',
        'documentazione_allegata' => 'documentazione_allegata',
        'giacenza_merci' => 'giacenza_merci',
        'annotazioni_mittente' => 'annotazioni_mittente',
        'annotazioni_interne' => 'annotazioni_interne',
        'proforma' => 'proforma',
        'urgente' => 'urgente',
        'email_contatto' => 'email_contatto',
        'cciaa' => 'cciaa'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'descrizione' => 'setDescrizione',
        'numero_copie' => 'setNumeroCopie',
        'modello_id' => 'setModelloId',
        'speditore' => 'setSpeditore',
        'destinatario' => 'setDestinatario',
        'paese_origine' => 'setPaeseOrigine',
        'trasporto' => 'setTrasporto',
        'osservazioni' => 'setOsservazioni',
        'merci' => 'setMerci',
        'quantita' => 'setQuantita',
        'paese_dest' => 'setPaeseDest',
        'valore_merce' => 'setValoreMerce',
        'numero_aut' => 'setNumeroAut',
        'paese_comunitario' => 'setPaeseComunitario',
        'produzione' => 'setProduzione',
        'azienda_produttrice' => 'setAziendaProduttrice',
        'modifiche' => 'setModifiche',
        'azienda_modifiche' => 'setAziendaModifiche',
        'paese_extraue' => 'setPaeseExtraue',
        'documentazione_allegata' => 'setDocumentazioneAllegata',
        'giacenza_merci' => 'setGiacenzaMerci',
        'annotazioni_mittente' => 'setAnnotazioniMittente',
        'annotazioni_interne' => 'setAnnotazioniInterne',
        'proforma' => 'setProforma',
        'urgente' => 'setUrgente',
        'email_contatto' => 'setEmailContatto',
        'cciaa' => 'setCciaa'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'descrizione' => 'getDescrizione',
        'numero_copie' => 'getNumeroCopie',
        'modello_id' => 'getModelloId',
        'speditore' => 'getSpeditore',
        'destinatario' => 'getDestinatario',
        'paese_origine' => 'getPaeseOrigine',
        'trasporto' => 'getTrasporto',
        'osservazioni' => 'getOsservazioni',
        'merci' => 'getMerci',
        'quantita' => 'getQuantita',
        'paese_dest' => 'getPaeseDest',
        'valore_merce' => 'getValoreMerce',
        'numero_aut' => 'getNumeroAut',
        'paese_comunitario' => 'getPaeseComunitario',
        'produzione' => 'getProduzione',
        'azienda_produttrice' => 'getAziendaProduttrice',
        'modifiche' => 'getModifiche',
        'azienda_modifiche' => 'getAziendaModifiche',
        'paese_extraue' => 'getPaeseExtraue',
        'documentazione_allegata' => 'getDocumentazioneAllegata',
        'giacenza_merci' => 'getGiacenzaMerci',
        'annotazioni_mittente' => 'getAnnotazioniMittente',
        'annotazioni_interne' => 'getAnnotazioniInterne',
        'proforma' => 'getProforma',
        'urgente' => 'getUrgente',
        'email_contatto' => 'getEmailContatto',
        'cciaa' => 'getCciaa'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('descrizione', $data ?? [], null);
        $this->setIfExists('numero_copie', $data ?? [], '0');
        $this->setIfExists('modello_id', $data ?? [], null);
        $this->setIfExists('speditore', $data ?? [], null);
        $this->setIfExists('destinatario', $data ?? [], null);
        $this->setIfExists('paese_origine', $data ?? [], null);
        $this->setIfExists('trasporto', $data ?? [], null);
        $this->setIfExists('osservazioni', $data ?? [], null);
        $this->setIfExists('merci', $data ?? [], null);
        $this->setIfExists('quantita', $data ?? [], null);
        $this->setIfExists('paese_dest', $data ?? [], '');
        $this->setIfExists('valore_merce', $data ?? [], '');
        $this->setIfExists('numero_aut', $data ?? [], '0');
        $this->setIfExists('paese_comunitario', $data ?? [], '');
        $this->setIfExists('produzione', $data ?? [], '');
        $this->setIfExists('azienda_produttrice', $data ?? [], null);
        $this->setIfExists('modifiche', $data ?? [], '');
        $this->setIfExists('azienda_modifiche', $data ?? [], null);
        $this->setIfExists('paese_extraue', $data ?? [], '');
        $this->setIfExists('documentazione_allegata', $data ?? [], null);
        $this->setIfExists('giacenza_merci', $data ?? [], '');
        $this->setIfExists('annotazioni_mittente', $data ?? [], null);
        $this->setIfExists('annotazioni_interne', $data ?? [], null);
        $this->setIfExists('proforma', $data ?? [], 'N');
        $this->setIfExists('urgente', $data ?? [], 'N');
        $this->setIfExists('email_contatto', $data ?? [], '');
        $this->setIfExists('cciaa', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['descrizione'] === null) {
            $invalidProperties[] = "'descrizione' can't be null";
        }
        if ((mb_strlen($this->container['descrizione']) > 255)) {
            $invalidProperties[] = "invalid value for 'descrizione', the character length must be smaller than or equal to 255.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets descrizione
     *
     * @return string
     */
    public function getDescrizione()
    {
        return $this->container['descrizione'];
    }

    /**
     * Sets descrizione
     *
     * @param string $descrizione descrizione
     *
     * @return self
     */
    public function setDescrizione($descrizione)
    {
        if (is_null($descrizione)) {
            throw new \InvalidArgumentException('non-nullable descrizione cannot be null');
        }
        if ((mb_strlen($descrizione) > 255)) {
            throw new \InvalidArgumentException('invalid length for $descrizione when calling V2richiesteStoreRequest., must be smaller than or equal to 255.');
        }

        $this->container['descrizione'] = $descrizione;

        return $this;
    }

    /**
     * Gets numero_copie
     *
     * @return string|null
     */
    public function getNumeroCopie()
    {
        return $this->container['numero_copie'];
    }

    /**
     * Sets numero_copie
     *
     * @param string|null $numero_copie numero_copie
     *
     * @return self
     */
    public function setNumeroCopie($numero_copie)
    {
        if (is_null($numero_copie)) {
            throw new \InvalidArgumentException('non-nullable numero_copie cannot be null');
        }
        $this->container['numero_copie'] = $numero_copie;

        return $this;
    }

    /**
     * Gets modello_id
     *
     * @return string|null
     */
    public function getModelloId()
    {
        return $this->container['modello_id'];
    }

    /**
     * Sets modello_id
     *
     * @param string|null $modello_id modello_id
     *
     * @return self
     */
    public function setModelloId($modello_id)
    {
        if (is_null($modello_id)) {
            throw new \InvalidArgumentException('non-nullable modello_id cannot be null');
        }
        $this->container['modello_id'] = $modello_id;

        return $this;
    }

    /**
     * Gets speditore
     *
     * @return string|null
     */
    public function getSpeditore()
    {
        return $this->container['speditore'];
    }

    /**
     * Sets speditore
     *
     * @param string|null $speditore speditore
     *
     * @return self
     */
    public function setSpeditore($speditore)
    {
        if (is_null($speditore)) {
            throw new \InvalidArgumentException('non-nullable speditore cannot be null');
        }
        $this->container['speditore'] = $speditore;

        return $this;
    }

    /**
     * Gets destinatario
     *
     * @return string|null
     */
    public function getDestinatario()
    {
        return $this->container['destinatario'];
    }

    /**
     * Sets destinatario
     *
     * @param string|null $destinatario destinatario
     *
     * @return self
     */
    public function setDestinatario($destinatario)
    {
        if (is_null($destinatario)) {
            throw new \InvalidArgumentException('non-nullable destinatario cannot be null');
        }
        $this->container['destinatario'] = $destinatario;

        return $this;
    }

    /**
     * Gets paese_origine
     *
     * @return string|null
     */
    public function getPaeseOrigine()
    {
        return $this->container['paese_origine'];
    }

    /**
     * Sets paese_origine
     *
     * @param string|null $paese_origine paese_origine
     *
     * @return self
     */
    public function setPaeseOrigine($paese_origine)
    {
        if (is_null($paese_origine)) {
            throw new \InvalidArgumentException('non-nullable paese_origine cannot be null');
        }
        $this->container['paese_origine'] = $paese_origine;

        return $this;
    }

    /**
     * Gets trasporto
     *
     * @return string|null
     */
    public function getTrasporto()
    {
        return $this->container['trasporto'];
    }

    /**
     * Sets trasporto
     *
     * @param string|null $trasporto trasporto
     *
     * @return self
     */
    public function setTrasporto($trasporto)
    {
        if (is_null($trasporto)) {
            throw new \InvalidArgumentException('non-nullable trasporto cannot be null');
        }
        $this->container['trasporto'] = $trasporto;

        return $this;
    }

    /**
     * Gets osservazioni
     *
     * @return string|null
     */
    public function getOsservazioni()
    {
        return $this->container['osservazioni'];
    }

    /**
     * Sets osservazioni
     *
     * @param string|null $osservazioni osservazioni
     *
     * @return self
     */
    public function setOsservazioni($osservazioni)
    {
        if (is_null($osservazioni)) {
            throw new \InvalidArgumentException('non-nullable osservazioni cannot be null');
        }
        $this->container['osservazioni'] = $osservazioni;

        return $this;
    }

    /**
     * Gets merci
     *
     * @return string|null
     */
    public function getMerci()
    {
        return $this->container['merci'];
    }

    /**
     * Sets merci
     *
     * @param string|null $merci merci
     *
     * @return self
     */
    public function setMerci($merci)
    {
        if (is_null($merci)) {
            throw new \InvalidArgumentException('non-nullable merci cannot be null');
        }
        $this->container['merci'] = $merci;

        return $this;
    }

    /**
     * Gets quantita
     *
     * @return string|null
     */
    public function getQuantita()
    {
        return $this->container['quantita'];
    }

    /**
     * Sets quantita
     *
     * @param string|null $quantita quantita
     *
     * @return self
     */
    public function setQuantita($quantita)
    {
        if (is_null($quantita)) {
            throw new \InvalidArgumentException('non-nullable quantita cannot be null');
        }
        $this->container['quantita'] = $quantita;

        return $this;
    }

    /**
     * Gets paese_dest
     *
     * @return string|null
     */
    public function getPaeseDest()
    {
        return $this->container['paese_dest'];
    }

    /**
     * Sets paese_dest
     *
     * @param string|null $paese_dest paese_dest
     *
     * @return self
     */
    public function setPaeseDest($paese_dest)
    {
        if (is_null($paese_dest)) {
            throw new \InvalidArgumentException('non-nullable paese_dest cannot be null');
        }
        $this->container['paese_dest'] = $paese_dest;

        return $this;
    }

    /**
     * Gets valore_merce
     *
     * @return string|null
     */
    public function getValoreMerce()
    {
        return $this->container['valore_merce'];
    }

    /**
     * Sets valore_merce
     *
     * @param string|null $valore_merce valore_merce
     *
     * @return self
     */
    public function setValoreMerce($valore_merce)
    {
        if (is_null($valore_merce)) {
            throw new \InvalidArgumentException('non-nullable valore_merce cannot be null');
        }
        $this->container['valore_merce'] = $valore_merce;

        return $this;
    }

    /**
     * Gets numero_aut
     *
     * @return string|null
     */
    public function getNumeroAut()
    {
        return $this->container['numero_aut'];
    }

    /**
     * Sets numero_aut
     *
     * @param string|null $numero_aut numero_aut
     *
     * @return self
     */
    public function setNumeroAut($numero_aut)
    {
        if (is_null($numero_aut)) {
            throw new \InvalidArgumentException('non-nullable numero_aut cannot be null');
        }
        $this->container['numero_aut'] = $numero_aut;

        return $this;
    }

    /**
     * Gets paese_comunitario
     *
     * @return string|null
     */
    public function getPaeseComunitario()
    {
        return $this->container['paese_comunitario'];
    }

    /**
     * Sets paese_comunitario
     *
     * @param string|null $paese_comunitario paese_comunitario
     *
     * @return self
     */
    public function setPaeseComunitario($paese_comunitario)
    {
        if (is_null($paese_comunitario)) {
            throw new \InvalidArgumentException('non-nullable paese_comunitario cannot be null');
        }
        $this->container['paese_comunitario'] = $paese_comunitario;

        return $this;
    }

    /**
     * Gets produzione
     *
     * @return string|null
     */
    public function getProduzione()
    {
        return $this->container['produzione'];
    }

    /**
     * Sets produzione
     *
     * @param string|null $produzione produzione
     *
     * @return self
     */
    public function setProduzione($produzione)
    {
        if (is_null($produzione)) {
            throw new \InvalidArgumentException('non-nullable produzione cannot be null');
        }
        $this->container['produzione'] = $produzione;

        return $this;
    }

    /**
     * Gets azienda_produttrice
     *
     * @return string|null
     */
    public function getAziendaProduttrice()
    {
        return $this->container['azienda_produttrice'];
    }

    /**
     * Sets azienda_produttrice
     *
     * @param string|null $azienda_produttrice azienda_produttrice
     *
     * @return self
     */
    public function setAziendaProduttrice($azienda_produttrice)
    {
        if (is_null($azienda_produttrice)) {
            throw new \InvalidArgumentException('non-nullable azienda_produttrice cannot be null');
        }
        $this->container['azienda_produttrice'] = $azienda_produttrice;

        return $this;
    }

    /**
     * Gets modifiche
     *
     * @return string|null
     */
    public function getModifiche()
    {
        return $this->container['modifiche'];
    }

    /**
     * Sets modifiche
     *
     * @param string|null $modifiche modifiche
     *
     * @return self
     */
    public function setModifiche($modifiche)
    {
        if (is_null($modifiche)) {
            throw new \InvalidArgumentException('non-nullable modifiche cannot be null');
        }
        $this->container['modifiche'] = $modifiche;

        return $this;
    }

    /**
     * Gets azienda_modifiche
     *
     * @return string|null
     */
    public function getAziendaModifiche()
    {
        return $this->container['azienda_modifiche'];
    }

    /**
     * Sets azienda_modifiche
     *
     * @param string|null $azienda_modifiche azienda_modifiche
     *
     * @return self
     */
    public function setAziendaModifiche($azienda_modifiche)
    {
        if (is_null($azienda_modifiche)) {
            throw new \InvalidArgumentException('non-nullable azienda_modifiche cannot be null');
        }
        $this->container['azienda_modifiche'] = $azienda_modifiche;

        return $this;
    }

    /**
     * Gets paese_extraue
     *
     * @return string|null
     */
    public function getPaeseExtraue()
    {
        return $this->container['paese_extraue'];
    }

    /**
     * Sets paese_extraue
     *
     * @param string|null $paese_extraue paese_extraue
     *
     * @return self
     */
    public function setPaeseExtraue($paese_extraue)
    {
        if (is_null($paese_extraue)) {
            throw new \InvalidArgumentException('non-nullable paese_extraue cannot be null');
        }
        $this->container['paese_extraue'] = $paese_extraue;

        return $this;
    }

    /**
     * Gets documentazione_allegata
     *
     * @return string|null
     */
    public function getDocumentazioneAllegata()
    {
        return $this->container['documentazione_allegata'];
    }

    /**
     * Sets documentazione_allegata
     *
     * @param string|null $documentazione_allegata documentazione_allegata
     *
     * @return self
     */
    public function setDocumentazioneAllegata($documentazione_allegata)
    {
        if (is_null($documentazione_allegata)) {
            throw new \InvalidArgumentException('non-nullable documentazione_allegata cannot be null');
        }
        $this->container['documentazione_allegata'] = $documentazione_allegata;

        return $this;
    }

    /**
     * Gets giacenza_merci
     *
     * @return string|null
     */
    public function getGiacenzaMerci()
    {
        return $this->container['giacenza_merci'];
    }

    /**
     * Sets giacenza_merci
     *
     * @param string|null $giacenza_merci giacenza_merci
     *
     * @return self
     */
    public function setGiacenzaMerci($giacenza_merci)
    {
        if (is_null($giacenza_merci)) {
            throw new \InvalidArgumentException('non-nullable giacenza_merci cannot be null');
        }
        $this->container['giacenza_merci'] = $giacenza_merci;

        return $this;
    }

    /**
     * Gets annotazioni_mittente
     *
     * @return string|null
     */
    public function getAnnotazioniMittente()
    {
        return $this->container['annotazioni_mittente'];
    }

    /**
     * Sets annotazioni_mittente
     *
     * @param string|null $annotazioni_mittente annotazioni_mittente
     *
     * @return self
     */
    public function setAnnotazioniMittente($annotazioni_mittente)
    {
        if (is_null($annotazioni_mittente)) {
            throw new \InvalidArgumentException('non-nullable annotazioni_mittente cannot be null');
        }
        $this->container['annotazioni_mittente'] = $annotazioni_mittente;

        return $this;
    }

    /**
     * Gets annotazioni_interne
     *
     * @return string|null
     */
    public function getAnnotazioniInterne()
    {
        return $this->container['annotazioni_interne'];
    }

    /**
     * Sets annotazioni_interne
     *
     * @param string|null $annotazioni_interne annotazioni_interne
     *
     * @return self
     */
    public function setAnnotazioniInterne($annotazioni_interne)
    {
        if (is_null($annotazioni_interne)) {
            throw new \InvalidArgumentException('non-nullable annotazioni_interne cannot be null');
        }
        $this->container['annotazioni_interne'] = $annotazioni_interne;

        return $this;
    }

    /**
     * Gets proforma
     *
     * @return string|null
     */
    public function getProforma()
    {
        return $this->container['proforma'];
    }

    /**
     * Sets proforma
     *
     * @param string|null $proforma proforma
     *
     * @return self
     */
    public function setProforma($proforma)
    {
        if (is_null($proforma)) {
            throw new \InvalidArgumentException('non-nullable proforma cannot be null');
        }
        $this->container['proforma'] = $proforma;

        return $this;
    }

    /**
     * Gets urgente
     *
     * @return string|null
     */
    public function getUrgente()
    {
        return $this->container['urgente'];
    }

    /**
     * Sets urgente
     *
     * @param string|null $urgente urgente
     *
     * @return self
     */
    public function setUrgente($urgente)
    {
        if (is_null($urgente)) {
            throw new \InvalidArgumentException('non-nullable urgente cannot be null');
        }
        $this->container['urgente'] = $urgente;

        return $this;
    }

    /**
     * Gets email_contatto
     *
     * @return string|null
     */
    public function getEmailContatto()
    {
        return $this->container['email_contatto'];
    }

    /**
     * Sets email_contatto
     *
     * @param string|null $email_contatto email_contatto
     *
     * @return self
     */
    public function setEmailContatto($email_contatto)
    {
        if (is_null($email_contatto)) {
            throw new \InvalidArgumentException('non-nullable email_contatto cannot be null');
        }
        $this->container['email_contatto'] = $email_contatto;

        return $this;
    }

    /**
     * Gets cciaa
     *
     * @return \OpenAPI\Client\Model\V2richiesteStoreRequestCciaa|null
     */
    public function getCciaa()
    {
        return $this->container['cciaa'];
    }

    /**
     * Sets cciaa
     *
     * @param \OpenAPI\Client\Model\V2richiesteStoreRequestCciaa|null $cciaa cciaa
     *
     * @return self
     */
    public function setCciaa($cciaa)
    {
        if (is_null($cciaa)) {
            throw new \InvalidArgumentException('non-nullable cciaa cannot be null');
        }
        $this->container['cciaa'] = $cciaa;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


