<?php
/**
 * RichiesteRichiestaBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Sprint - Documentazione
 *
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.71
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * RichiesteRichiestaBodyTest Class Doc Comment
 *
 * @category    Class
 * @description RichiesteRichiestaBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RichiesteRichiestaBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RichiesteRichiestaBody"
     */
    public function testRichiesteRichiestaBody()
    {
    }

    /**
     * Test attribute "descrizione"
     */
    public function testPropertyDescrizione()
    {
    }

    /**
     * Test attribute "speditore"
     */
    public function testPropertySpeditore()
    {
    }

    /**
     * Test attribute "destinatario"
     */
    public function testPropertyDestinatario()
    {
    }

    /**
     * Test attribute "paese_origine"
     */
    public function testPropertyPaeseOrigine()
    {
    }

    /**
     * Test attribute "informazioni"
     */
    public function testPropertyInformazioni()
    {
    }

    /**
     * Test attribute "osservazioni"
     */
    public function testPropertyOsservazioni()
    {
    }

    /**
     * Test attribute "paese_dest"
     */
    public function testPropertyPaeseDest()
    {
    }

    /**
     * Test attribute "numero_copie"
     */
    public function testPropertyNumeroCopie()
    {
    }

    /**
     * Test attribute "trasporto"
     */
    public function testPropertyTrasporto()
    {
    }

    /**
     * Test attribute "merci"
     */
    public function testPropertyMerci()
    {
    }

    /**
     * Test attribute "quantita"
     */
    public function testPropertyQuantita()
    {
    }

    /**
     * Test attribute "valore_merce"
     */
    public function testPropertyValoreMerce()
    {
    }

    /**
     * Test attribute "numero_aut"
     */
    public function testPropertyNumeroAut()
    {
    }

    /**
     * Test attribute "paese_comunitario"
     */
    public function testPropertyPaeseComunitario()
    {
    }

    /**
     * Test attribute "produzione"
     */
    public function testPropertyProduzione()
    {
    }

    /**
     * Test attribute "azienda_produttrice"
     */
    public function testPropertyAziendaProduttrice()
    {
    }

    /**
     * Test attribute "modifiche"
     */
    public function testPropertyModifiche()
    {
    }

    /**
     * Test attribute "azienda_modifiche"
     */
    public function testPropertyAziendaModifiche()
    {
    }

    /**
     * Test attribute "paese_extraue"
     */
    public function testPropertyPaeseExtraue()
    {
    }

    /**
     * Test attribute "documentazione_allegata"
     */
    public function testPropertyDocumentazioneAllegata()
    {
    }

    /**
     * Test attribute "giacenza_merci"
     */
    public function testPropertyGiacenzaMerci()
    {
    }

    /**
     * Test attribute "annotazioni_mittente"
     */
    public function testPropertyAnnotazioniMittente()
    {
    }

    /**
     * Test attribute "annotazioni_interne"
     */
    public function testPropertyAnnotazioniInterne()
    {
    }

    /**
     * Test attribute "proforma"
     */
    public function testPropertyProforma()
    {
    }

    /**
     * Test attribute "urgente"
     */
    public function testPropertyUrgente()
    {
    }

    /**
     * Test attribute "email_contatto"
     */
    public function testPropertyEmailContatto()
    {
    }

    /**
     * Test attribute "cciaa"
     */
    public function testPropertyCciaa()
    {
    }
}
