<?php
/**
 * V2modelliUpdateRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IBSWebCO\Sprint
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Sprint - Documentazione
 *
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace IBSWebCO\Sprint\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V2modelliUpdateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description V2modelliUpdateRequest
 * @package     IBSWebCO\Sprint
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V2modelliUpdateRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V2modelliUpdateRequest"
     */
    public function testV2modelliUpdateRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descrizione"
     */
    public function testPropertyDescrizione()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "speditore"
     */
    public function testPropertySpeditore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "destinatario"
     */
    public function testPropertyDestinatario()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trasporto"
     */
    public function testPropertyTrasporto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "osservazioni"
     */
    public function testPropertyOsservazioni()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paeseDestinazione"
     */
    public function testPropertyPaeseDestinazione()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "aziendaProduttrice"
     */
    public function testPropertyAziendaProduttrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "aziendaModifiche"
     */
    public function testPropertyAziendaModifiche()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "documentazioneAllegata"
     */
    public function testPropertyDocumentazioneAllegata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "giacenzaMerci"
     */
    public function testPropertyGiacenzaMerci()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ncopie"
     */
    public function testPropertyNcopie()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nvisti"
     */
    public function testPropertyNvisti()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nleg"
     */
    public function testPropertyNleg()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fattFirmata"
     */
    public function testPropertyFattFirmata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "notecciaa"
     */
    public function testPropertyNotecciaa()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
