<?php
/**
 * V2richiesteStoreRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IBSWebCO\Sprint
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Sprint - Documentazione
 *
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace IBSWebCO\Sprint\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V2richiesteStoreRequestTest Class Doc Comment
 *
 * @category    Class
 * @description V2richiesteStoreRequest
 * @package     IBSWebCO\Sprint
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V2richiesteStoreRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V2richiesteStoreRequest"
     */
    public function testV2richiesteStoreRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descrizione"
     */
    public function testPropertyDescrizione()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numeroCopie"
     */
    public function testPropertyNumeroCopie()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "modelloId"
     */
    public function testPropertyModelloId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "speditore"
     */
    public function testPropertySpeditore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "destinatario"
     */
    public function testPropertyDestinatario()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paeseOrigine"
     */
    public function testPropertyPaeseOrigine()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trasporto"
     */
    public function testPropertyTrasporto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "osservazioni"
     */
    public function testPropertyOsservazioni()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "merci"
     */
    public function testPropertyMerci()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantita"
     */
    public function testPropertyQuantita()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paeseDest"
     */
    public function testPropertyPaeseDest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valoreMerce"
     */
    public function testPropertyValoreMerce()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numeroAut"
     */
    public function testPropertyNumeroAut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paeseComunitario"
     */
    public function testPropertyPaeseComunitario()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "produzione"
     */
    public function testPropertyProduzione()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "aziendaProduttrice"
     */
    public function testPropertyAziendaProduttrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "modifiche"
     */
    public function testPropertyModifiche()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "aziendaModifiche"
     */
    public function testPropertyAziendaModifiche()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paeseExtraue"
     */
    public function testPropertyPaeseExtraue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "documentazioneAllegata"
     */
    public function testPropertyDocumentazioneAllegata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "giacenzaMerci"
     */
    public function testPropertyGiacenzaMerci()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "annotazioniMittente"
     */
    public function testPropertyAnnotazioniMittente()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "annotazioniInterne"
     */
    public function testPropertyAnnotazioniInterne()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "proforma"
     */
    public function testPropertyProforma()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "urgente"
     */
    public function testPropertyUrgente()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emailContatto"
     */
    public function testPropertyEmailContatto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cciaa"
     */
    public function testPropertyCciaa()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
