<?php
/**
 * V2vistiStoreRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  IBSWebCO\Sprint
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Sprint - Documentazione
 *
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace IBSWebCO\Sprint\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V2vistiStoreRequestTest Class Doc Comment
 *
 * @category    Class
 * @description V2vistiStoreRequest
 * @package     IBSWebCO\Sprint
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V2vistiStoreRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V2vistiStoreRequest"
     */
    public function testV2vistiStoreRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descrizione"
     */
    public function testPropertyDescrizione()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "annotazioniMittente"
     */
    public function testPropertyAnnotazioniMittente()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "stampaAzienda"
     */
    public function testPropertyStampaAzienda()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
