<?php
/**
 * RichiestaApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Sprint - Documentazione
 *
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.71
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RichiestaApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RichiestaApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v2richiesteDestroy
     *
     * Remove the specified resource from storage.
     *
     */
    public function testV2richiesteDestroy()
    {
    }

    /**
     * Test case for v2richiesteIndex
     *
     * Display a listing of the resource.
     *
     */
    public function testV2richiesteIndex()
    {
    }

    /**
     * Test case for v2richiesteShow
     *
     * Display the specified resource.
     *
     */
    public function testV2richiesteShow()
    {
    }

    /**
     * Test case for v2richiesteStore
     *
     * Store a newly created resource in storage.
     *
     */
    public function testV2richiesteStore()
    {
    }

    /**
     * Test case for v2richiesteUpdate
     *
     * Update the specified resource in storage.
     *
     */
    public function testV2richiesteUpdate()
    {
    }
}
